-- Migration: Create static stock tables for Supabase
-- Generated on 2026-05-26

-- 1. stocks table (static master list)
CREATE TABLE IF NOT EXISTS public.stocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    company_name TEXT NOT NULL,
    exchange TEXT NOT NULL CHECK (exchange IN ('NSE', 'BSE')),
    sector TEXT NOT NULL,
    instrument_key TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Ensure symbol uniqueness (you may also want a unique constraint on instrument_key)
CREATE UNIQUE INDEX IF NOT EXISTS idx_stocks_symbol ON public.stocks (symbol);
CREATE UNIQUE INDEX IF NOT EXISTS idx_stocks_instrument_key ON public.stocks (instrument_key);

-- 2. watchlist table (optional, per‑user list of favourite symbols)
CREATE TABLE IF NOT EXISTS public.watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    symbol TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_watchlist_symbol FOREIGN KEY (symbol) REFERENCES public.stocks (symbol) ON DELETE CASCADE,
    CONSTRAINT fk_watchlist_user FOREIGN KEY (user_id) REFERENCES auth.users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_watchlist_user ON public.watchlist (user_id);
CREATE INDEX IF NOT EXISTS idx_watchlist_symbol ON public.watchlist (symbol);

-- 3. stock_metadata table (optional, slow‑changing metadata)
CREATE TABLE IF NOT EXISTS public.stock_metadata (
    symbol TEXT NOT NULL PRIMARY KEY,
    market_cap NUMERIC,
    eps NUMERIC,
    pe_ratio NUMERIC,
    industry TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
    CONSTRAINT fk_metadata_symbol FOREIGN KEY (symbol) REFERENCES public.stocks (symbol) ON DELETE CASCADE
);

-- Trigger to update `updated_at` on row modification for stocks and stock_metadata
CREATE OR REPLACE FUNCTION public.update_timestamp()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_stocks_update
BEFORE UPDATE ON public.stocks
FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();

CREATE TRIGGER trg_stock_metadata_update
BEFORE UPDATE ON public.stock_metadata
FOR EACH ROW EXECUTE FUNCTION public.update_timestamp();

-- Note: Supabase automatically exposes these tables via the REST API and client libraries.
-- You can now populate `public.stocks` with the static master list (symbol, company_name, exchange, sector, instrument_key).
